### ISSUE TITLE
Add fast-path for exporting png/jpeg textures without going through Skia bitmap

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveResourceFormat#601]
There's no reason to re-encode the image to png when it's already a png. Should also make it faster.

**Comment by chescos** [comment]
Just tested it. The exported PNG file now has the same SHA1 hash in CS2 and CSGO (CS2 file is vtex_c, CSGO file is plain png). So it seems to restore the original file, as intended.

**Comment by chescos** [comment]
Hey @xPaw - I noticed one issue with `VTEX_FORMAT_BGRA8888` files. They are originally also PNG files but still seem to get decoded and not restored to their original. Do you think it would be possible to restore the original file for `VTEX_FORMAT_BGRA8888` as well?

**Comment by xPaw** [comment]
That's not png.

**Comment by chescos** [comment]
Is this an error on Valve's part then? Because the original is definitely a .png file, at least Valve stores it as PNG.

One example is the `./panorama/images/econ/stickers/antwerp2022/astr_graffiti_large_png.vtex_c` of the CS2 pak01:

VTEX File: https://media.chescos.me/uploads/znUOcc2VNZUxSxhF7oplOOOXwjRO1LQfibvxapjYl3OS2DjI2hDl0PLu4RxNNz6Y.vtex_c

CDN PNG file: https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/boston2018/nor_graffiti_large.d662f7dbecd1c0c20e0c5cb11bf595ef5c8d39c5.png

When opening the `vtex_c` in VRF, it shows up as `VTEX_FORMAT_BGRA8888`.

**Comment by xPaw** [comment]
There's no error and there's no need for them to compile it as png if they don't need it.
