### ISSUE TITLE
Missing tint colors in decompiled map (need to split models)

### ISSUE THREAD

**Issue by kristiker** [ValveResourceFormat/ValveResourceFormat#643]
### Describe the bug

In VMAP_C decompile. It seems that since models are clumped together, they can't have proper tints assigned. 

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

maps/de_dust2.vpk

### Expected behavior

I expect the models to be split up and assigned an individual tint and alpha.

### What version of VRF are you using? On what platform?

5.0

**Comment by TheHeavynator** [comment]
objects being merged together wouldnt be the issue here, its simply that these tint colors arent exported. [kristiker](https://github.com/kristiker) mentioned this in a previous post.
"Btw VertexColor in the viewer mostly displays _object tint_. Tints are indeed not exported in glTF. Maybe it can be exported as a single-attribute vertex color stream."
